class LocKeys:
    # Cmd start 
    START_MSG='START_MSG'

    # Cmd coquo
    COQUO_OPTIONS='COQUO_OPTIONS'
    COQUO_FINISHED='COQUO_FINISHED'

    # Cmd get order
    GET_ORDER_TITLE_FULL_ORDER='TITLE_FULL_ORDER'
    GET_ORDER_TITLE_GET_USERS='GET_ORDER_USERS'
    GET_ORDER_MISSING_PRICE='GET_ORDER_MISSING_PRICE'
    GET_ORDER_TOTAL_PRICE='GET_ORDER_TOTAL_PRICE'
    GET_ORDER_MISSING_ARGS='GET_ORDER_MISSING_ARGS'
    GET_ORDER_TOO_MUCH_ARGS='GET_ORDER_TOO_MUCH_ARGS'

    # Cmd get order divided
    GET_ORDER_DIVIDED_TITLE='GET_ORDER_DIVIDED_TITLE'
    GET_ORDER_DIVIDED_USER_ORDER='GET_ORDER_DIVIDED_USER_ORDER'

    # Cmd order
    ORDER_FINISH_TITLE='ORDER_FINISH_TITLE'
    ORDER_MSG='ORDER_MSG'
    ORDER_ITEM_ADDED='ORDER_ITEM_ADDED'

    # Cmd reset order
    ORDER_RESET_DONE='ORDER_RESET_DONE'

    # Cmd edit order
    EDIT_ORDER_TITLE_UPDATED='EDIT_ORDER_UPDATED'
    EDIT_ORDER_USER_ORDER='EDIT_ORDER_USER_ORDER'
    EDIT_ORDER_EMPTY='EDIT_ORDER_EMPTY'

    # Cmd add order
    ADD_ORDER_MISSING_ARGS='ADD_ORDER_MISSING_ARGS'
    ADD_ORDER_ITEMS_ADDED='ADD_ORDER_ITEMS_ADDED'

    # Cmd add order me
    ADD_ORDER_ME_MISSING_ARGS='ADD_ORDER_ME_MISSING_ARGS'

    # Cmd info
    INFO_SCHEDULE='INFO_SCHEDULE'

    # Btn
    BTN_MENU='BTN_MENU'
    BTN_WEB='BTN_WEB'
    BTN_ORDER='BTN_ORDER'
    BTN_EDIT_ORDER='BTN_EDIT_ORDER'
    BTN_RESET_ORDER='BTN_RESET_ORDER'
    BTN_GET_FULL_ORDER='BTN_GET_FULL_ORDER'
    BTN_GET_MY_ORDER='BTN_GET_MY_ORDER'
    BTN_FINISH='BTN_FINISH'
    BTN_DIVIDED_ORDER='BTN_DIVIDED_ORDER'