class LocKeys:
    # Cmd start 
    START_MSG='START_MSG'

    # Cmd coquo
    COQUO_OPTIONS='COQUO_OPTIONS'
    COQUO_FINISHED='COQUO_FINISHED'

    ORDER_RESET_DONE='ORDER_RESET_DONE'

    # Btn
    BTN_MENU='BTN_MENU'
    BTN_WEB='BTN_WEB'
    BTN_ORDER='BTN_ORDER'
    BTN_EDIT_ORDER='BTN_EDIT_ORDER'
    BTN_RESET_ORDER='BTN_RESET_ORDER'
    BTN_GET_FULL_ORDER='BTN_GET_FULL_ORDER'
    BTN_GET_MY_ORDER='BTN_GET_MY_ORDER'
    BTN_FINISH='BTN_FINISH'